---
title: "4.- Data Exploration"
author: "Andrew.Z.Flores"
date: "4/26/2020"
output: html_document
---

```{r, load_libraries}
library(tidyverse)
library(lattice)
library(ggrepel)
library(GGally)
library(reshape2)

```

```{r, load_data}
unique_subset <- read.csv("transformed_unique_mcdi_cumul.subset.csv")
unique_subset <- unique_subset %>% filter(Word != "penis")

unique_subset.16 <- unique_subset %>% filter(Age == 16)
unique_subset.24 <- unique_subset %>% filter(Age == 24)

```
# Single Age Group Graphs
## Facet Graphs(MCDIp by Distributional Predictor)
### Scatter Plot
```{r, MCDIP_Frequency}


unique_subset.24 <- unique_subset.24 %>% select(Word,Lexical_Class,MCDIp,Lexical_Diversity,Document_Diversity,ProKWo,logCummulative_Frequency)

colnames(unique_subset.24) <-c("Word","Lexical Class","MCDIp","Lexical Diversity","Document Diversity","Pro-KWo","Frequency")

unique_subset.24 <- unique_subset.24 %>% select(Word,`Lexical Class`,MCDIp,Frequency,`Lexical Diversity`,`Document Diversity`,`Pro-KWo`)

unique_subset.24$MCDIp <- as.factor(unique_subset.24$MCDIp)

unique_subset.24.melt <- melt(unique_subset.24, by = c("Word","Lexical Class","MCDIp"))

unique_subset.24.melt$MCDIp <- as.numeric(as.character(unique_subset.24.melt$MCDIp))


#plot 
Scatter_Plot.24 <-unique_subset.24.melt %>%  
  ggplot(aes(x=value, y= MCDIp, color = `Lexical Class`)) 

Scatter_Plot.24 <- Scatter_Plot.24 + geom_point() 

Scatter_Plot.24 <- Scatter_Plot.24 + scale_color_manual(labels =c("Adjectives","Function", "Nouns","Verbs"), values = c("#ffd125","#6fafc7","#bfd46d","#ee5e5e")
)

Scatter_Plot.24<- Scatter_Plot.24 + facet_wrap(~ variable, scales = "free" ,ncol = 1) + theme_bw() 


Scatter_Plot.24<- Scatter_Plot.24  + theme(text = element_text(size=20, face = "bold", hjust = 0.5), legend.position = "top", legend.title = element_blank(), axis.title.x=element_blank())



# Save
ggsave(Scatter_Plot.24, file = "Scatter_Plot.24.jpeg",dpi = "retina", width = 210, height = 297, units = "mm" )
```

### Scatter Plot.square
```{r, MCDIP_Frequency_Square}


unique_subset.24 <- unique_subset.24 %>% select(Word,`Lexical Class`,MCDIp,`Lexical Diversity`,`Document Diversity`,`Pro-KWo`,Frequency)

colnames(unique_subset.24) <-c("Word","Lexical Class","MCDIp","Lexical Diversity","Document Diversity","Pro-KWo","Frequency")

unique_subset.24 <- unique_subset.24 %>% select(Word,`Lexical Class`,MCDIp,Frequency,`Lexical Diversity`,`Document Diversity`,`Pro-KWo`)

unique_subset.24$MCDIp <- as.factor(unique_subset.24$MCDIp)

unique_subset.24.melt <- melt(unique_subset.24, by = c("Word","Lexical Class","MCDIp"))

unique_subset.24.melt$MCDIp <- as.numeric(as.character(unique_subset.24.melt$MCDIp))


#plot 
Scatter_Plot.24 <-unique_subset.24.melt %>%  
  ggplot(aes(x=value, y= MCDIp, color = `Lexical Class`)) 

Scatter_Plot.24 <- Scatter_Plot.24 + geom_point() 

Scatter_Plot.24 <- Scatter_Plot.24 + scale_color_manual(labels =c("Adjectives","Function", "Nouns","Verbs"), values = c("#ffd125","#6fafc7","#bfd46d","#ee5e5e")
)

Scatter_Plot.24<- Scatter_Plot.24 + facet_wrap(~ variable, scales = "free" ,ncol = 2,nrow = 2) + theme_bw() 


Scatter_Plot.24<- Scatter_Plot.24  + theme(text = element_text(size=20, face = "bold", hjust = 0.5), legend.position = "top", legend.title = element_blank(), axis.title.x=element_blank())



# Save
ggsave(Scatter_Plot.24, file = "Scatter_Plot.24_sq.jpeg",dpi = "retina", width = 13, height = 13)
```


### Label Plot
```{r}
#plot 
Label_Plot.24 <-unique_subset.24.melt %>%  
  ggplot(aes(x=value, y= MCDIp, fill = `Lexical Class`)) 

Label_Plot.24 <- Label_Plot.24 + geom_label(aes(label = Word), label.size = 0.01) 

Label_Plot.24 <- Label_Plot.24 + scale_fill_manual(labels =c("Adjectives","Function", "Nouns","Verbs"), values = c("#ffd125","#6fafc7","#bfd46d","#ee5e5e")
)

#LONG
Label_Plot.24<- Label_Plot.24 + facet_wrap(~ variable, scales = "free", ncol = 1) + theme_bw() 

#WIDE
Label_Plot.24<- Label_Plot.24 + facet_wrap(~ variable, scales = "free", ncol = 1) + theme_bw() 

Label_Plot.24<- Label_Plot.24  + theme(text = element_text(size=20, face = "bold", hjust = 0.5), legend.position = "top", legend.title = element_blank(), axis.title.x=element_blank())


# Save (LONG)
ggsave(Label_Plot.24, file = "Label_Plot.24(LONG).jpeg",dpi = "retina", width = 210, height = 297, units = "mm")

# Save (Wide)
#ggsave(Label_Plot.24, file = "Label_Plot.24(WIDE).jpeg",dpi = "retina", width = 297, height = 210, units = "mm")

```

### Label Plot.squre
```{r, square}
#plot 
Label_Plot.24 <-unique_subset.24.melt %>%  
  ggplot(aes(x=value, y= MCDIp, fill = `Lexical Class`)) 

Label_Plot.24 <- Label_Plot.24 + geom_label(aes(label = Word), label.size = 0.01) 

Label_Plot.24 <- Label_Plot.24 + scale_fill_manual(labels =c("Adjectives","Function", "Nouns","Verbs"), values = c("#ffd125","#6fafc7","#bfd46d","#ee5e5e")
)



#WIDE
Label_Plot.24<- Label_Plot.24 + facet_wrap(~ variable, scales = "free", ncol = 2, nrow = 2) + theme_bw() 

Label_Plot.24<- Label_Plot.24  + theme(text = element_text(size=20, face = "bold", hjust = 0.5), legend.position = "top", legend.title = element_blank(), axis.title.x=element_blank())

# Save (LONG)
ggsave(Label_Plot.24, file = "Label_Plot.24_sq.jpeg",dpi = "retina", width = 13, height = 13)

```

# Multiple Age Group Graphs

### Distribution Matrices
```{r, Age by Predictor Density Plot Matrix}
Age_Predictor_Matrix_data <- unique_subset %>% select(Age,MCDIp,logCummulative_Frequency,Lexical_Diversity,Document_Diversity,ProKWo,ProKWo_Shuffle) 

colnames(Age_Predictor_Matrix_data) <-c("Age","MCDIp","Frequency","Lexical Diversity","Document Diversity","Pro-KWo","Pro-KWo Shuffle")



Age_Predictor_Matrix_data <-  Age_Predictor_Matrix_data %>% gather(key = "Predictor", value =  "Predictor Value",Frequency:`Pro-KWo Shuffle`)

Age_Predictor_Matrix_data$Predictor = factor(Age_Predictor_Matrix_data$Predictor, levels=c("Frequency","Lexical Diversity","Document Diversity","Pro-KWo","Pro-KWo Shuffle"))

#Age_Predictor_Matrix_data <- Age_Predictor_Matrix_data %>% filter(Predictor != "`Pro-KWo Shuffle`")

#create plot

Age_Predictor_Matrix.plot <- Age_Predictor_Matrix_data %>% ggplot(aes(x = `Predictor Value`,y = MCDIp, color = Predictor)) + geom_point()

#set rows
Age_Predictor_Matrix.plot <- Age_Predictor_Matrix.plot + facet_grid(rows = vars(Age))

#set columns
Age_Predictor_Matrix.plot <- Age_Predictor_Matrix.plot + facet_grid(cols = vars(Predictor))



#complete matrix
Age_Predictor_Matrix.plot <- Age_Predictor_Matrix.plot + facet_grid(vars(Age),vars(Predictor),scales = "free")

#add theme
Age_Predictor_Matrix.plot <- Age_Predictor_Matrix.plot + theme_minimal() + theme(legend.position= "none",text = element_text(size=18, face = "bold", hjust = 0.5))


Age_Predictor_Matrix.plot <- Age_Predictor_Matrix.plot+ scale_color_manual(values = c("#eeb1a2","#02a699","#f45c51","#274dc6","#000000")
)


ggsave(Age_Predictor_Matrix.plot, file = "Figure 1. Age and Predictor Matrix plot.jpeg", dpi = "retina" ,width = 210, height = 297,units = "mm")

 ggsave(Age_Predictor_Matrix.plot, file = "Figure 1. Age and Predictor Matrix plot.S.jpeg",dpi = "retina", width = 14, height = 14)

```

### Correlation Line Graph 
```{r, reshape}

#select desired columns
unique_subset_Cross.Sectional <- unique_subset %>% select(Age,Lexical_Class,MCDIp_logCummulative_Frequency.lex,MCDIp_Lexical_Diversity.lex,MCDIp_Document_Diversity.lex,MCDIp_ProKWo.lex,MCDIp_ProKWo_Shuffle.lex,Lexical_Class,MCDIp_logCummulative_Frequency.all,MCDIp_Lexical_Diversity.all,MCDIp_Document_Diversity.all,MCDIp_ProKWo.all,MCDIp_ProKWo_Shuffle.all)

#reshape in order to plot
unique_subset_Cross.Sectional<- melt(unique_subset_Cross.Sectional, id=c("Age","Lexical_Class"))

#remove duplicate values
unique_subset_Cross.Sectional <- unique(unique_subset_Cross.Sectional)

# Add Lexical category "All"
unique_subset_Cross.Sectional <- unique_subset_Cross.Sectional %>% mutate(Lexical_Class = case_when(grepl("all", variable)~ "All",TRUE ~as.character(Lexical_Class)))

#Make variable names less obtuse...
unique_subset_Cross.Sectional <- unique_subset_Cross.Sectional %>% mutate(measure = case_when(grepl("MCDIp_ProKWo.all", variable)~ "Pro-KWo",grepl("MCDIp_ProKWo.lex", variable)~ "Pro-KWo",grepl("Frequency",variable) ~ "Frequency", grepl("Lexical", variable)~ "Lexical Diversity", grepl("Document_Diversity", variable) ~ "Document Diversity", grepl("MCDIp_ProKWo_Shuffle.all", variable) ~ "Pro-KWo Shuffle",grepl("MCDIp_ProKWo_Shuffle.lex", variable) ~ "Pro-KWo Shuffle"))

# Subset of data that does not include lexical class
unique_subset_Cross_Sectional.All <- unique_subset_Cross.Sectional %>% filter(Lexical_Class == "All")

#subset of data that includes lexical class
#variables <- c("ProKWo","Frequency")
#unique_subset_Cross_Sectional.lex <-filter(unique_subset_Cross.Sectional, measure %in% variables)

```

```{r}
unique_subset_Cross.Sectional$Age <- as.factor(unique_subset_Cross.Sectional$Age)
unique_subset_Cross.Sectional <- unique(unique_subset_Cross.Sectional)

#unique_subset_Cross.Sectional <- unique_subset_Cross.Sectional %>% filter(measure!= "ProKWoShuffle")



unique_subset_Cross.Sectional$measure = factor(unique_subset_Cross.Sectional$measure, levels=c("Frequency","Lexical Diversity","Document Diversity","Pro-KWo","Pro-KWo Shuffle"))

p <- ggplot(data=unique_subset_Cross.Sectional,
            mapping = aes(x = Age,
                          y = value,
                          color= Lexical_Class))

p<- p + geom_line(aes(group = Lexical_Class)) + facet_wrap(~ measure, nrow = 1)

p <- p + labs( x = "Age (mo)" , y = "Pearson correlation (r)", color = "Lexical Class")     

p <- p + scale_color_manual(labels =c("Adjectives","All","Function","Nouns","Verbs"), values = c("#ffd125","#000000","#6fafc7","#bfd46d","#ee5e5e"))

  
p <- p +  theme_bw() + theme(legend.position= "top",text = element_text(size=20, face = "bold", hjust = 0.5))










ggsave(p, filename = "wide.jpeg", width = 14, height = 7)
```


