---
title: "6b.- Raw Data Analyzed Graphics"
author: "Andrew.Z.Flores"
date: "5/4/2020"
output: html_document
---
#Setup
```{r, libraries}
library(tidyverse)
```

#Load Data

## Overall model performance
```{r}
# Logistic Regression Null Models

model1_performance<- read_csv("model1_performance.csv")
model2_performance<- read_csv("model2_performance.csv")
model3_performance<- read_csv("model3_performance.csv")
model4_performance<- read_csv("model4_performance.csv")
model5_performance<- read_csv("model5_performance.csv")


# Null Multilevel Logistic Regression

model5.5_performance <- read_csv("model5.5_performance.csv")

# HLM Logistic Regression
model6_performance<- read_csv("model6_performance.csv")
model7_performance<- read_csv("model7_performance.csv")
model8_performance<- read_csv("model8_performance.csv")
model9_performance<- read_csv("model9_performance.csv")

#Null 3-level logistic regression analysis
Model9.5_performance <- read_csv("model9.5_performance.csv")

# 3-level logistic regression analysis 
Model10_performance <- read_csv("model10_performance.csv")

# 3-level logistic regression analysis with cross-level interaction(ProKWo*Frequency)
Model11_performance <- read_csv("model11_performance.csv")

# ACROSS age groups
Model13_performance <- read_csv("model13_performance.csv")
```

### Merge appropriate model comparisons.

```{r, merge model performances}
# Logistic Regression Null Models
Logistic_Null_Models.performance <- full_join(model1_performance,model2_performance)

Logistic_Null_Models.performance <-  Logistic_Null_Models.performance %>% full_join(model3_performance) %>% full_join(model4_performance) %>% full_join(model5_performance)


# HLM Logistic Regression Models

HLM_Logistic_Models.performance <- full_join(model5.5_performance,model6_performance)
HLM_Logistic_Models.performance <- HLM_Logistic_Models.performance %>% full_join(model7_performance) %>% full_join(model8_performance) %>% full_join(model9_performance)


# 3-level HLM Logistic Regression Models

three_level_HLM_Logistic_Models.performance <- full_join(Model9.5_performance,Model10_performance)
three_level_HLM_Logistic_Models.performance <- three_level_HLM_Logistic_Models.performance %>% full_join(Model11_performance)

write.csv(Logistic_Null_Models.performance, file = "Logistic_Null_Models_performance.csv", row.names = F)
write.csv(HLM_Logistic_Models.performance, file = "HLM_Logistic_Models_performance.csv", row.names = F)
write.csv(three_level_HLM_Logistic_Models.performance, file = "Three_level_HLM_Logistic_Models.csv", row.names = F)
```

## Estimates
```{r}
# Logistic Regression Null Models

model1_effects<- read_csv("model1_effects.csv")
model2_effects<- read_csv("model2_effects.csv")
model3_effects<- read_csv("model3_effects.csv")
model4_effects<- read_csv("model4_effects.csv")
model5_effects<- read_csv("model5_effects.csv")


# Null Multilevel Logistic Regression

model5.5_effects <- read_csv("model5.5_effects.csv")

# HLM Logistic Regression
model6_effects<- read_csv("model6_effects.csv")
model7_effects<- read_csv("model7_effects.csv")
model8_effects<- read_csv("model8_effects.csv")
model9_effects<- read_csv("model9_effects.csv")

#Null 3-level logistic regression analysis
Model9.5_effects <- read_csv("model9.5_effects.csv")

# 3-level logistic regression analysis 
Model10_effects <- read_csv("model10_effects.csv")

# 3-level logistic regression analysis with cross-level interaction(ProKWo*Frequency)
Model11_effects <- read_csv("model11_effects.csv")

# ACROSS age groups
Model13_effects <- read_csv("model13_effects.csv")
```

### Merge appropriate model comparisons.
```{r, merge model performances}
# Logistic Regression Null Models
Logistic_Null_Models.effects <- full_join(model1_effects,model2_effects)

Logistic_Null_Models.effects <-  Logistic_Null_Models.effects %>% full_join(model3_effects) %>% full_join(model4_effects) %>% full_join(model5_effects)


# HLM Logistic Regression Models

HLM_Logistic_Models.effects <- full_join(model5.5_effects,model6_effects)
HLM_Logistic_Models.effects <- HLM_Logistic_Models.effects %>% full_join(model7_effects) %>% full_join(model8_effects) %>% full_join(model9_effects)


# 3-level HLM Logistic Regression Models

three_level_HLM_Logistic_Models.effects <- full_join(Model9.5_effects,Model10_effects)
three_level_HLM_Logistic_Models.effects <- three_level_HLM_Logistic_Models.effects %>% full_join(Model11_effects)

write.csv(Logistic_Null_Models.effects, file = "Logistic_Null_Models_effects.csv", row.names = F)
write.csv(HLM_Logistic_Models.effects, file = "HLM_Logistic_Models_effects.csv", row.names = F)
write.csv(three_level_HLM_Logistic_Models.effects, file = "Three_level_HLM_Logistic_Models.effects.csv", row.names = F)
```


## Estimates.odds
```{r}
# Logistic Regression Null Models
model1_odds.effects<- read_csv("model1_odds.effects.csv")
model2_odds.effects<- read_csv("model2_odds.effects.csv")
model3_odds.effects<- read_csv("model3_odds.effects.csv")
model4_odds.effects<- read_csv("model4_odds.effects.csv")
model5_odds.effects<- read_csv("model5_odds.effects.csv")


# Null Multilevel Logistic Regression
model5.5_odds.effects <- read_csv("model5.5_effects.csv")

# HLM Logistic Regression
model6_odds.effects<- read_csv("model6_odds.effects.csv")
model7_odds.effects<- read_csv("model7_odds.effects.csv")
model8_odds.effects<- read_csv("model8_odds.effects.csv")
model9_odds.effects<- read_csv("model9_odds.effects.csv")

#Null 3-level logistic regression analysis
Model9.5_odds.effects <- read_csv("model9.5_odds.effects.csv")

# 3-level logistic regression analysis 
Model10_odds.effects <- read_csv("model10_odds.effects.csv")

# 3-level logistic regression analysis with cross-level interaction(ProKWo*Frequency)
Model11_odds.effects <- read_csv("model11_odds.effects.csv")

# ACROSS age groups
Model13_odds.effects <- read_csv("model13_odds.effects.csv")
```


```{r, merge model performances}
# Logistic Regression Null Models
Logistic_Null_Models_odds.effects <- full_join(model1_odds.effects,model2_odds.effects)

Logistic_Null_Models_odds.effects <-  Logistic_Null_Models_odds.effects %>% full_join(model3_odds.effects) %>% full_join(model4_odds.effects) %>% full_join(model5_odds.effects)


# HLM Logistic Regression Models

HLM_Logistic_Models_odds.effects <- full_join(model5.5_odds.effects,model6_odds.effects)
HLM_Logistic_Models_odds.effects <- Logistic_Null_Models_odds.effects %>% full_join(model7_odds.effects) %>% full_join(model8_odds.effects) %>% full_join(model9_odds.effects)


# 3-level HLM Logistic Regression Models

three_level_HLM_Logistic_Models_odds.effects <- full_join(Model9.5_odds.effects,Model10_odds.effects)
three_level_HLM_Logistic_Models_odds.effects <- three_level_HLM_Logistic_Models_odds.effects %>% full_join(Model11_odds.effects)

write.csv(Logistic_Null_Models_odds.effects, file = "Logistic_Null_Models_odds.effects.csv", row.names = F)
write.csv(HLM_Logistic_Models_odds.effects, file = "HLM_Logistic_Models_odds.effects.csv", row.names = F)
write.csv(three_level_HLM_Logistic_Models_odds.effects, file = "Three_level_HLM_Logistic_Models_odds.effects.csv", row.names = F)
```




