---
title: "6b.- Raw Data Analyzed Graphics"
author: "Andrew.Z.Flores"
date: "5/4/2020"
output: html_document
---
#Setup
```{r, libraries}
library(tidyverse)
library(gt)
library(glue)
library(forcats)
library(knitr)
library(kableExtra)
```

```{r}
model14_data <- read_csv("model14_effects.csv")
model14_data <- model14_data %>% select(Age,Estimate,Model.x,value,std.error,p,`2.5%`,`97.5%`)
```

# 3 level Model Table
```{r}
model_14.wide <- model14_data %>% mutate(significance = if_else(p <= 0.05,"*"," "))
model_14.wide <- model_14.wide %>% mutate(value = signif(value,3)) %>% mutate(std.error = signif(std.error,2))
model_14.wide <- model_14.wide %>% mutate(Estimate = case_when(grepl("Lexical_Diversity",Estimate)~"Lexical Diversity",grepl("Document_Diversity",Estimate)~"Document Diversity", grepl("ProKWo_Shuffle",Estimate)~"Pro-KWo Shuffle",grepl("ProKWo",Estimate)~"Pro-KWo",TRUE ~as.character(.$Estimate)))

model_14.wide[,5] <- paste0("(", format(unlist(model_14.wide[,5])),")")

model_14.wide$value <- as.double(model_14.wide$value)

model_14.wide <- model_14.wide %>% unite(sep= "",estimate_value, c("value","significance")) 

model_14.wide <- model_14.wide %>% unite(sep= " ",Parameter, c("estimate_value","std.error"))
model_14.wide <- model_14.wide %>% select(Estimate,Age,Parameter)

model_14.wide <- model_14.wide %>% spread(Age,Parameter)

#reorder factors

model_14.wide$Estimate <- as.factor(model_14.wide$Estimate)

model_14.wide <- model_14.wide[c(3,2,4,1,5,6),]

colnames(model_14.wide) <-c("Parameter","18","21","24","27","30")

# Make Table
model_14.wide %>% gt()%>% gtsave("table.png")
```





```{r}
model14_data$Age <- as.factor(model14_data$Age)
model14_data <- model14_data %>% filter(Estimate != "Intercept")
model14_data <- as.data.frame(model14_data)
```

# Single Predictor estimate plot w/ 95% CI
```{r}

model14_data <- model14_data %>% mutate(Estimate = fct_relevel(Estimate,
                                                               "Frequency",
                                                               "Lexical_Diversity",
                                                               "Document_Diversity",
                                                               "ProKWo",
                                                               "ProKWo_Shuffle"
                                                              ))


model14.plot <- ggplot(data=model14_data, 
                       aes(x = Age,
                           y = value, 
                           group = Estimate)) 

model14.plot <- model14.plot + geom_pointrange(ymin = model14_data$`2.5%` ,ymax= model14_data$`97.5%`)

  
model14.plot <- model14.plot + geom_line(aes(color = Estimate)) + geom_point(aes(color = Estimate))

model14.plot <- model14.plot + scale_color_manual(values = c("#eeb1a2","#02a699","#f45c51","#274dc6","#000000"), labels = c("Frequency", "Lexical Diversity", "Document Diversity", "Pro-KWo","Pro-KWo Shuffle"))

model14.plot <- model14.plot + labs( x = "Age (mo)" , y = "Estimate Value")     

model14.plot <- model14.plot + theme_classic() 

model14.plot <- model14.plot + theme(text = element_text(size=20, hjust = 0.5), legend.position = "right", legend.title = element_blank())



ggsave(model14.plot, file= "Cross Random Effects Model Comparison.jpeg", width = 14, height = 7)
```




