
```{r, load_libraries}
library(tidyverse)
library(lattice)
library(ggrepel)
library(GGally)
library(reshape2)

```

```{r, load_data}
unique_subset <- read.csv("transformed_unique_mcdi_cumul.subset.csv")

# remove outliers that severly impact correlation values
unique_subset <- unique_subset %>% filter(Word != "penis")
unique_subset <- unique_subset %>% filter(Word != "i")

unique_subset.16 <- unique_subset %>% filter(Age == 16)
unique_subset.24 <- unique_subset %>% filter(Age == 24)

```

```{r}
unique_subset.24 <- unique_subset.24 %>% select(Word,Lexical_Class,MCDIp,Lexical_Diversity,Document_Diversity,ProKWo,logCummulative_Frequency)

colnames(unique_subset.24) <-c("Word","Lexical Class","MCDIp","Lexical Diversity","Document Diversity","Pro-KWo","Frequency")

unique_subset.24 <- unique_subset.24 %>% select(Word,`Lexical Class`,MCDIp,Frequency,`Lexical Diversity`,`Document Diversity`,`Pro-KWo`)

unique_subset.24$MCDIp <- as.factor(unique_subset.24$MCDIp)

unique_subset.24.melt <- melt(unique_subset.24, by = c("Word","Lexical Class","MCDIp"))

unique_subset.24.melt$MCDIp <- as.numeric(as.character(unique_subset.24.melt$MCDIp))

```

### Label Plot.squre
```{r, square}
#plot 
Label_Plot.24 <-unique_subset.24.melt %>%  
  ggplot(aes(x=value, y= MCDIp, fill = `Lexical Class`)) 

Label_Plot.24 <- Label_Plot.24 + geom_label(aes(label = Word), label.size = 0.01) 

Label_Plot.24 <- Label_Plot.24 + scale_fill_manual(labels =c("Adjectives","Function", "Nouns","Verbs"), values = c("#ffd125","#6fafc7","#bfd46d","#ee5e5e")
)

Label_Plot.24<- Label_Plot.24 + facet_wrap(~ variable, scales = "free", ncol = 2, nrow = 2) + theme_bw() 

Label_Plot.24<- Label_Plot.24  + theme(text = element_text(size=20, face = "bold", hjust = 0.5), legend.position = "top", legend.title = element_blank(), axis.title.x=element_blank())

ggsave(Label_Plot.24, file = "Figure 2. MCDIp Scores at 24 months.jpeg",dpi = "retina", width = 13, height = 13)
```
